'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PaymentModule")>  _
Partial Public Class AppDocumentsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InserttblApplicationType(instance As tblApplicationType)
    End Sub
  Partial Private Sub UpdatetblApplicationType(instance As tblApplicationType)
    End Sub
  Partial Private Sub DeletetblApplicationType(instance As tblApplicationType)
    End Sub
  Partial Private Sub InserttblDocumentType(instance As tblDocumentType)
    End Sub
  Partial Private Sub UpdatetblDocumentType(instance As tblDocumentType)
    End Sub
  Partial Private Sub DeletetblDocumentType(instance As tblDocumentType)
    End Sub
  Partial Private Sub InserttblMemberApplication(instance As tblMemberApplication)
    End Sub
  Partial Private Sub UpdatetblMemberApplication(instance As tblMemberApplication)
    End Sub
  Partial Private Sub DeletetblMemberApplication(instance As tblMemberApplication)
    End Sub
  Partial Private Sub InserttblSPLog(instance As tblSPLog)
    End Sub
  Partial Private Sub UpdatetblSPLog(instance As tblSPLog)
    End Sub
  Partial Private Sub DeletetblSPLog(instance As tblSPLog)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("PaymentModuleConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tblApplicationTypes() As System.Data.Linq.Table(Of tblApplicationType)
		Get
			Return Me.GetTable(Of tblApplicationType)
		End Get
	End Property
	
	Public ReadOnly Property tblDocumentTypes() As System.Data.Linq.Table(Of tblDocumentType)
		Get
			Return Me.GetTable(Of tblDocumentType)
		End Get
	End Property
	
	Public ReadOnly Property tblAppDocumentTypes() As System.Data.Linq.Table(Of tblAppDocumentType)
		Get
			Return Me.GetTable(Of tblAppDocumentType)
		End Get
	End Property
	
	Public ReadOnly Property tblMemberApplications() As System.Data.Linq.Table(Of tblMemberApplication)
		Get
			Return Me.GetTable(Of tblMemberApplication)
		End Get
	End Property
	
	Public ReadOnly Property tblSPLogs() As System.Data.Linq.Table(Of tblSPLog)
		Get
			Return Me.GetTable(Of tblSPLog)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblApplicationType")>  _
Partial Public Class tblApplicationType
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiAppTypeId As Integer
	
	Private _txtDescription As String
	
	Private _tblMemberApplications As EntitySet(Of tblMemberApplication)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiAppTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiAppTypeIdChanged()
    End Sub
    Partial Private Sub OntxtDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OntxtDescriptionChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblMemberApplications = New EntitySet(Of tblMemberApplication)(AddressOf Me.attach_tblMemberApplications, AddressOf Me.detach_tblMemberApplications)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiAppTypeId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property pkiAppTypeId() As Integer
		Get
			Return Me._pkiAppTypeId
		End Get
		Set
			If ((Me._pkiAppTypeId = value)  _
						= false) Then
				Me.OnpkiAppTypeIdChanging(value)
				Me.SendPropertyChanging
				Me._pkiAppTypeId = value
				Me.SendPropertyChanged("pkiAppTypeId")
				Me.OnpkiAppTypeIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtDescription", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property txtDescription() As String
		Get
			Return Me._txtDescription
		End Get
		Set
			If (String.Equals(Me._txtDescription, value) = false) Then
				Me.OntxtDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._txtDescription = value
				Me.SendPropertyChanged("txtDescription")
				Me.OntxtDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblApplicationType_tblMemberApplication", Storage:="_tblMemberApplications", ThisKey:="pkiAppTypeId", OtherKey:="fkiAppTypeId")>  _
	Public Property tblMemberApplications() As EntitySet(Of tblMemberApplication)
		Get
			Return Me._tblMemberApplications
		End Get
		Set
			Me._tblMemberApplications.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_tblMemberApplications(ByVal entity As tblMemberApplication)
		Me.SendPropertyChanging
		entity.tblApplicationType = Me
	End Sub
	
	Private Sub detach_tblMemberApplications(ByVal entity As tblMemberApplication)
		Me.SendPropertyChanging
		entity.tblApplicationType = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblDocumentType")>  _
Partial Public Class tblDocumentType
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiDocumentTypeID As Integer
	
	Private _txtDocumentName As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiDocumentTypeIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiDocumentTypeIDChanged()
    End Sub
    Partial Private Sub OntxtDocumentNameChanging(value As String)
    End Sub
    Partial Private Sub OntxtDocumentNameChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiDocumentTypeID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property pkiDocumentTypeID() As Integer
		Get
			Return Me._pkiDocumentTypeID
		End Get
		Set
			If ((Me._pkiDocumentTypeID = value)  _
						= false) Then
				Me.OnpkiDocumentTypeIDChanging(value)
				Me.SendPropertyChanging
				Me._pkiDocumentTypeID = value
				Me.SendPropertyChanged("pkiDocumentTypeID")
				Me.OnpkiDocumentTypeIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtDocumentName", DbType:="VarChar(300) NOT NULL", CanBeNull:=false)>  _
	Public Property txtDocumentName() As String
		Get
			Return Me._txtDocumentName
		End Get
		Set
			If (String.Equals(Me._txtDocumentName, value) = false) Then
				Me.OntxtDocumentNameChanging(value)
				Me.SendPropertyChanging
				Me._txtDocumentName = value
				Me.SendPropertyChanged("txtDocumentName")
				Me.OntxtDocumentNameChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblAppDocumentType")>  _
Partial Public Class tblAppDocumentType
	
	Private _pkiAppDocTypeID As Integer
	
	Private _appTypeID As System.Nullable(Of Integer)
	
	Private _fkiDocumentTypeID As System.Nullable(Of Integer)
	
	Private _txtSector As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiAppDocTypeID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property pkiAppDocTypeID() As Integer
		Get
			Return Me._pkiAppDocTypeID
		End Get
		Set
			If ((Me._pkiAppDocTypeID = value)  _
						= false) Then
				Me._pkiAppDocTypeID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appTypeID", DbType:="Int")>  _
	Public Property appTypeID() As System.Nullable(Of Integer)
		Get
			Return Me._appTypeID
		End Get
		Set
			If (Me._appTypeID.Equals(value) = false) Then
				Me._appTypeID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiDocumentTypeID", DbType:="Int")>  _
	Public Property fkiDocumentTypeID() As System.Nullable(Of Integer)
		Get
			Return Me._fkiDocumentTypeID
		End Get
		Set
			If (Me._fkiDocumentTypeID.Equals(value) = false) Then
				Me._fkiDocumentTypeID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtSector", DbType:="VarChar(10)")>  _
	Public Property txtSector() As String
		Get
			Return Me._txtSector
		End Get
		Set
			If (String.Equals(Me._txtSector, value) = false) Then
				Me._txtSector = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblMemberApplication")>  _
Partial Public Class tblMemberApplication
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiMemberApplicationID As Integer
	
	Private _txtApplicationCode As String
	
	Private _fkiMemberID As Integer
	
	Private _txtPIN As String
	
	Private _txtFullName As String
	
	Private _txtEmployerName As String
	
	Private _txtSex As String
	
	Private _dteDOB As System.Nullable(Of Date)
	
	Private _fkiAppTypeId As Integer
	
	Private _txtSector As String
	
	Private _dteCreated As Date
	
	Private _dteApplicationDate As Date
	
	Private _txtStatus As String
	
	Private _txtCreatedBy As String
	
	Private _dteDOR As System.Nullable(Of Date)
	
	Private _dteDisengagement As System.Nullable(Of Date)
	
	Private _txtComment As String
	
	Private _txtApplicationState As String
	
	Private _txtApplicationOffice As String
	
	Private _numFinalSalary As System.Nullable(Of Decimal)
	
	Private _dteStatusChange As System.Nullable(Of Date)
	
	Private _IsRejected As System.Nullable(Of Boolean)
	
	Private _IsDocCompleted As System.Nullable(Of Boolean)
	
	Private _IsSentToPencom As System.Nullable(Of Boolean)
	
	Private _dteSentToPencom As System.Nullable(Of Date)
	
	Private _txtPencomBatch As String
	
	Private _txtSPBatchNo As String
	
	Private _dteDocumentCompleted As System.Nullable(Of Date)
	
	Private _dteProcessing As System.Nullable(Of Date)
	
	Private _dteConfirmed As System.Nullable(Of Date)
	
	Private _dtePaid As System.Nullable(Of Date)
	
	Private _dteApproved As System.Nullable(Of Date)
	
	Private _dteTerminated As System.Nullable(Of Date)
	
	Private _numRSABalance As System.Nullable(Of Decimal)
	
	Private _numLumpSum As System.Nullable(Of Decimal)
	
	Private _numMonthlyPW As System.Nullable(Of Decimal)
	
	Private _numPremium As System.Nullable(Of Decimal)
	
	Private _numAnnuity As System.Nullable(Of Decimal)
	
	Private _dteConfirmPriceDate As System.Nullable(Of Date)
	
	Private _txtReason As String
	
	Private _fkiEmployerID As System.Nullable(Of Integer)
	
	Private _txtEmployerCode As String
	
	Private _txtDepartment As String
	
	Private _txtDesignation As String
	
	Private _txtInsuranceCompany As String
	
	Private _txtLastChangedPerson As String
	
	Private _txtAccountName As String
	
	Private _txtAccountNo As String
	
	Private _txtBVN As String
	
	Private _fkiBankID As System.Nullable(Of Integer)
	
	Private _fkiBranchID As System.Nullable(Of Integer)
	
	Private _txtCommentGroup As String
	
	Private _txtFundStatus As String
	
	Private _IsDeactivated As System.Nullable(Of Boolean)
	
	Private _dteDeactivated As System.Nullable(Of Date)
	
	Private _txtDeactivatedBy As String
	
	Private _tblApplicationType As EntityRef(Of tblApplicationType)
	
	Private _tblSPLog As EntityRef(Of tblSPLog)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiMemberApplicationIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiMemberApplicationIDChanged()
    End Sub
    Partial Private Sub OntxtApplicationCodeChanging(value As String)
    End Sub
    Partial Private Sub OntxtApplicationCodeChanged()
    End Sub
    Partial Private Sub OnfkiMemberIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnfkiMemberIDChanged()
    End Sub
    Partial Private Sub OntxtPINChanging(value As String)
    End Sub
    Partial Private Sub OntxtPINChanged()
    End Sub
    Partial Private Sub OntxtFullNameChanging(value As String)
    End Sub
    Partial Private Sub OntxtFullNameChanged()
    End Sub
    Partial Private Sub OntxtEmployerNameChanging(value As String)
    End Sub
    Partial Private Sub OntxtEmployerNameChanged()
    End Sub
    Partial Private Sub OntxtSexChanging(value As String)
    End Sub
    Partial Private Sub OntxtSexChanged()
    End Sub
    Partial Private Sub OndteDOBChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDOBChanged()
    End Sub
    Partial Private Sub OnfkiAppTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnfkiAppTypeIdChanged()
    End Sub
    Partial Private Sub OntxtSectorChanging(value As String)
    End Sub
    Partial Private Sub OntxtSectorChanged()
    End Sub
    Partial Private Sub OndteCreatedChanging(value As Date)
    End Sub
    Partial Private Sub OndteCreatedChanged()
    End Sub
    Partial Private Sub OndteApplicationDateChanging(value As Date)
    End Sub
    Partial Private Sub OndteApplicationDateChanged()
    End Sub
    Partial Private Sub OntxtStatusChanging(value As String)
    End Sub
    Partial Private Sub OntxtStatusChanged()
    End Sub
    Partial Private Sub OntxtCreatedByChanging(value As String)
    End Sub
    Partial Private Sub OntxtCreatedByChanged()
    End Sub
    Partial Private Sub OndteDORChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDORChanged()
    End Sub
    Partial Private Sub OndteDisengagementChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDisengagementChanged()
    End Sub
    Partial Private Sub OntxtCommentChanging(value As String)
    End Sub
    Partial Private Sub OntxtCommentChanged()
    End Sub
    Partial Private Sub OntxtApplicationStateChanging(value As String)
    End Sub
    Partial Private Sub OntxtApplicationStateChanged()
    End Sub
    Partial Private Sub OntxtApplicationOfficeChanging(value As String)
    End Sub
    Partial Private Sub OntxtApplicationOfficeChanged()
    End Sub
    Partial Private Sub OnnumFinalSalaryChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumFinalSalaryChanged()
    End Sub
    Partial Private Sub OndteStatusChangeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteStatusChangeChanged()
    End Sub
    Partial Private Sub OnIsRejectedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsRejectedChanged()
    End Sub
    Partial Private Sub OnIsDocCompletedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsDocCompletedChanged()
    End Sub
    Partial Private Sub OnIsSentToPencomChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsSentToPencomChanged()
    End Sub
    Partial Private Sub OndteSentToPencomChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteSentToPencomChanged()
    End Sub
    Partial Private Sub OntxtPencomBatchChanging(value As String)
    End Sub
    Partial Private Sub OntxtPencomBatchChanged()
    End Sub
    Partial Private Sub OntxtSPBatchNoChanging(value As String)
    End Sub
    Partial Private Sub OntxtSPBatchNoChanged()
    End Sub
    Partial Private Sub OndteDocumentCompletedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDocumentCompletedChanged()
    End Sub
    Partial Private Sub OndteProcessingChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteProcessingChanged()
    End Sub
    Partial Private Sub OndteConfirmedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteConfirmedChanged()
    End Sub
    Partial Private Sub OndtePaidChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndtePaidChanged()
    End Sub
    Partial Private Sub OndteApprovedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteApprovedChanged()
    End Sub
    Partial Private Sub OndteTerminatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteTerminatedChanged()
    End Sub
    Partial Private Sub OnnumRSABalanceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumRSABalanceChanged()
    End Sub
    Partial Private Sub OnnumLumpSumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumLumpSumChanged()
    End Sub
    Partial Private Sub OnnumMonthlyPWChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumMonthlyPWChanged()
    End Sub
    Partial Private Sub OnnumPremiumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumPremiumChanged()
    End Sub
    Partial Private Sub OnnumAnnuityChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnnumAnnuityChanged()
    End Sub
    Partial Private Sub OndteConfirmPriceDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteConfirmPriceDateChanged()
    End Sub
    Partial Private Sub OntxtReasonChanging(value As String)
    End Sub
    Partial Private Sub OntxtReasonChanged()
    End Sub
    Partial Private Sub OnfkiEmployerIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfkiEmployerIDChanged()
    End Sub
    Partial Private Sub OntxtEmployerCodeChanging(value As String)
    End Sub
    Partial Private Sub OntxtEmployerCodeChanged()
    End Sub
    Partial Private Sub OntxtDepartmentChanging(value As String)
    End Sub
    Partial Private Sub OntxtDepartmentChanged()
    End Sub
    Partial Private Sub OntxtDesignationChanging(value As String)
    End Sub
    Partial Private Sub OntxtDesignationChanged()
    End Sub
    Partial Private Sub OntxtInsuranceCompanyChanging(value As String)
    End Sub
    Partial Private Sub OntxtInsuranceCompanyChanged()
    End Sub
    Partial Private Sub OntxtLastChangedPersonChanging(value As String)
    End Sub
    Partial Private Sub OntxtLastChangedPersonChanged()
    End Sub
    Partial Private Sub OntxtAccountNameChanging(value As String)
    End Sub
    Partial Private Sub OntxtAccountNameChanged()
    End Sub
    Partial Private Sub OntxtAccountNoChanging(value As String)
    End Sub
    Partial Private Sub OntxtAccountNoChanged()
    End Sub
    Partial Private Sub OntxtBVNChanging(value As String)
    End Sub
    Partial Private Sub OntxtBVNChanged()
    End Sub
    Partial Private Sub OnfkiBankIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfkiBankIDChanged()
    End Sub
    Partial Private Sub OnfkiBranchIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfkiBranchIDChanged()
    End Sub
    Partial Private Sub OntxtCommentGroupChanging(value As String)
    End Sub
    Partial Private Sub OntxtCommentGroupChanged()
    End Sub
    Partial Private Sub OntxtFundStatusChanging(value As String)
    End Sub
    Partial Private Sub OntxtFundStatusChanged()
    End Sub
    Partial Private Sub OnIsDeactivatedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsDeactivatedChanged()
    End Sub
    Partial Private Sub OndteDeactivatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDeactivatedChanged()
    End Sub
    Partial Private Sub OntxtDeactivatedByChanging(value As String)
    End Sub
    Partial Private Sub OntxtDeactivatedByChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblApplicationType = CType(Nothing, EntityRef(Of tblApplicationType))
		Me._tblSPLog = CType(Nothing, EntityRef(Of tblSPLog))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiMemberApplicationID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property pkiMemberApplicationID() As Integer
		Get
			Return Me._pkiMemberApplicationID
		End Get
		Set
			If ((Me._pkiMemberApplicationID = value)  _
						= false) Then
				Me.OnpkiMemberApplicationIDChanging(value)
				Me.SendPropertyChanging
				Me._pkiMemberApplicationID = value
				Me.SendPropertyChanged("pkiMemberApplicationID")
				Me.OnpkiMemberApplicationIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtApplicationCode", DbType:="VarChar(50)")>  _
	Public Property txtApplicationCode() As String
		Get
			Return Me._txtApplicationCode
		End Get
		Set
			If (String.Equals(Me._txtApplicationCode, value) = false) Then
				Me.OntxtApplicationCodeChanging(value)
				Me.SendPropertyChanging
				Me._txtApplicationCode = value
				Me.SendPropertyChanged("txtApplicationCode")
				Me.OntxtApplicationCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiMemberID", DbType:="Int NOT NULL")>  _
	Public Property fkiMemberID() As Integer
		Get
			Return Me._fkiMemberID
		End Get
		Set
			If ((Me._fkiMemberID = value)  _
						= false) Then
				Me.OnfkiMemberIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiMemberID = value
				Me.SendPropertyChanged("fkiMemberID")
				Me.OnfkiMemberIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtPIN", DbType:="VarChar(20)")>  _
	Public Property txtPIN() As String
		Get
			Return Me._txtPIN
		End Get
		Set
			If (String.Equals(Me._txtPIN, value) = false) Then
				Me.OntxtPINChanging(value)
				Me.SendPropertyChanging
				Me._txtPIN = value
				Me.SendPropertyChanged("txtPIN")
				Me.OntxtPINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtFullName", DbType:="VarChar(255)")>  _
	Public Property txtFullName() As String
		Get
			Return Me._txtFullName
		End Get
		Set
			If (String.Equals(Me._txtFullName, value) = false) Then
				Me.OntxtFullNameChanging(value)
				Me.SendPropertyChanging
				Me._txtFullName = value
				Me.SendPropertyChanged("txtFullName")
				Me.OntxtFullNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtEmployerName", DbType:="VarChar(255)")>  _
	Public Property txtEmployerName() As String
		Get
			Return Me._txtEmployerName
		End Get
		Set
			If (String.Equals(Me._txtEmployerName, value) = false) Then
				Me.OntxtEmployerNameChanging(value)
				Me.SendPropertyChanging
				Me._txtEmployerName = value
				Me.SendPropertyChanged("txtEmployerName")
				Me.OntxtEmployerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtSex", DbType:="Char(5)")>  _
	Public Property txtSex() As String
		Get
			Return Me._txtSex
		End Get
		Set
			If (String.Equals(Me._txtSex, value) = false) Then
				Me.OntxtSexChanging(value)
				Me.SendPropertyChanging
				Me._txtSex = value
				Me.SendPropertyChanged("txtSex")
				Me.OntxtSexChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDOB", DbType:="DateTime")>  _
	Public Property dteDOB() As System.Nullable(Of Date)
		Get
			Return Me._dteDOB
		End Get
		Set
			If (Me._dteDOB.Equals(value) = false) Then
				Me.OndteDOBChanging(value)
				Me.SendPropertyChanging
				Me._dteDOB = value
				Me.SendPropertyChanged("dteDOB")
				Me.OndteDOBChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiAppTypeId", DbType:="Int NOT NULL")>  _
	Public Property fkiAppTypeId() As Integer
		Get
			Return Me._fkiAppTypeId
		End Get
		Set
			If ((Me._fkiAppTypeId = value)  _
						= false) Then
				If Me._tblApplicationType.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnfkiAppTypeIdChanging(value)
				Me.SendPropertyChanging
				Me._fkiAppTypeId = value
				Me.SendPropertyChanged("fkiAppTypeId")
				Me.OnfkiAppTypeIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtSector", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property txtSector() As String
		Get
			Return Me._txtSector
		End Get
		Set
			If (String.Equals(Me._txtSector, value) = false) Then
				Me.OntxtSectorChanging(value)
				Me.SendPropertyChanging
				Me._txtSector = value
				Me.SendPropertyChanged("txtSector")
				Me.OntxtSectorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteCreated", DbType:="DateTime NOT NULL")>  _
	Public Property dteCreated() As Date
		Get
			Return Me._dteCreated
		End Get
		Set
			If ((Me._dteCreated = value)  _
						= false) Then
				Me.OndteCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dteCreated = value
				Me.SendPropertyChanged("dteCreated")
				Me.OndteCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteApplicationDate", DbType:="DateTime NOT NULL")>  _
	Public Property dteApplicationDate() As Date
		Get
			Return Me._dteApplicationDate
		End Get
		Set
			If ((Me._dteApplicationDate = value)  _
						= false) Then
				Me.OndteApplicationDateChanging(value)
				Me.SendPropertyChanging
				Me._dteApplicationDate = value
				Me.SendPropertyChanged("dteApplicationDate")
				Me.OndteApplicationDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtStatus", DbType:="VarChar(50)")>  _
	Public Property txtStatus() As String
		Get
			Return Me._txtStatus
		End Get
		Set
			If (String.Equals(Me._txtStatus, value) = false) Then
				Me.OntxtStatusChanging(value)
				Me.SendPropertyChanging
				Me._txtStatus = value
				Me.SendPropertyChanged("txtStatus")
				Me.OntxtStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCreatedBy", DbType:="VarChar(50)")>  _
	Public Property txtCreatedBy() As String
		Get
			Return Me._txtCreatedBy
		End Get
		Set
			If (String.Equals(Me._txtCreatedBy, value) = false) Then
				Me.OntxtCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._txtCreatedBy = value
				Me.SendPropertyChanged("txtCreatedBy")
				Me.OntxtCreatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDOR", DbType:="DateTime")>  _
	Public Property dteDOR() As System.Nullable(Of Date)
		Get
			Return Me._dteDOR
		End Get
		Set
			If (Me._dteDOR.Equals(value) = false) Then
				Me.OndteDORChanging(value)
				Me.SendPropertyChanging
				Me._dteDOR = value
				Me.SendPropertyChanged("dteDOR")
				Me.OndteDORChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDisengagement", DbType:="DateTime")>  _
	Public Property dteDisengagement() As System.Nullable(Of Date)
		Get
			Return Me._dteDisengagement
		End Get
		Set
			If (Me._dteDisengagement.Equals(value) = false) Then
				Me.OndteDisengagementChanging(value)
				Me.SendPropertyChanging
				Me._dteDisengagement = value
				Me.SendPropertyChanged("dteDisengagement")
				Me.OndteDisengagementChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtComment", DbType:="VarChar(1000)")>  _
	Public Property txtComment() As String
		Get
			Return Me._txtComment
		End Get
		Set
			If (String.Equals(Me._txtComment, value) = false) Then
				Me.OntxtCommentChanging(value)
				Me.SendPropertyChanging
				Me._txtComment = value
				Me.SendPropertyChanged("txtComment")
				Me.OntxtCommentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtApplicationState", DbType:="VarChar(50)")>  _
	Public Property txtApplicationState() As String
		Get
			Return Me._txtApplicationState
		End Get
		Set
			If (String.Equals(Me._txtApplicationState, value) = false) Then
				Me.OntxtApplicationStateChanging(value)
				Me.SendPropertyChanging
				Me._txtApplicationState = value
				Me.SendPropertyChanged("txtApplicationState")
				Me.OntxtApplicationStateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtApplicationOffice", DbType:="VarChar(50)")>  _
	Public Property txtApplicationOffice() As String
		Get
			Return Me._txtApplicationOffice
		End Get
		Set
			If (String.Equals(Me._txtApplicationOffice, value) = false) Then
				Me.OntxtApplicationOfficeChanging(value)
				Me.SendPropertyChanging
				Me._txtApplicationOffice = value
				Me.SendPropertyChanged("txtApplicationOffice")
				Me.OntxtApplicationOfficeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numFinalSalary", DbType:="Decimal(18,2)")>  _
	Public Property numFinalSalary() As System.Nullable(Of Decimal)
		Get
			Return Me._numFinalSalary
		End Get
		Set
			If (Me._numFinalSalary.Equals(value) = false) Then
				Me.OnnumFinalSalaryChanging(value)
				Me.SendPropertyChanging
				Me._numFinalSalary = value
				Me.SendPropertyChanged("numFinalSalary")
				Me.OnnumFinalSalaryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteStatusChange", DbType:="DateTime")>  _
	Public Property dteStatusChange() As System.Nullable(Of Date)
		Get
			Return Me._dteStatusChange
		End Get
		Set
			If (Me._dteStatusChange.Equals(value) = false) Then
				Me.OndteStatusChangeChanging(value)
				Me.SendPropertyChanging
				Me._dteStatusChange = value
				Me.SendPropertyChanged("dteStatusChange")
				Me.OndteStatusChangeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsRejected", DbType:="Bit")>  _
	Public Property IsRejected() As System.Nullable(Of Boolean)
		Get
			Return Me._IsRejected
		End Get
		Set
			If (Me._IsRejected.Equals(value) = false) Then
				Me.OnIsRejectedChanging(value)
				Me.SendPropertyChanging
				Me._IsRejected = value
				Me.SendPropertyChanged("IsRejected")
				Me.OnIsRejectedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDocCompleted", DbType:="Bit")>  _
	Public Property IsDocCompleted() As System.Nullable(Of Boolean)
		Get
			Return Me._IsDocCompleted
		End Get
		Set
			If (Me._IsDocCompleted.Equals(value) = false) Then
				Me.OnIsDocCompletedChanging(value)
				Me.SendPropertyChanging
				Me._IsDocCompleted = value
				Me.SendPropertyChanged("IsDocCompleted")
				Me.OnIsDocCompletedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsSentToPencom", DbType:="Bit")>  _
	Public Property IsSentToPencom() As System.Nullable(Of Boolean)
		Get
			Return Me._IsSentToPencom
		End Get
		Set
			If (Me._IsSentToPencom.Equals(value) = false) Then
				Me.OnIsSentToPencomChanging(value)
				Me.SendPropertyChanging
				Me._IsSentToPencom = value
				Me.SendPropertyChanged("IsSentToPencom")
				Me.OnIsSentToPencomChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteSentToPencom", DbType:="DateTime")>  _
	Public Property dteSentToPencom() As System.Nullable(Of Date)
		Get
			Return Me._dteSentToPencom
		End Get
		Set
			If (Me._dteSentToPencom.Equals(value) = false) Then
				Me.OndteSentToPencomChanging(value)
				Me.SendPropertyChanging
				Me._dteSentToPencom = value
				Me.SendPropertyChanged("dteSentToPencom")
				Me.OndteSentToPencomChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtPencomBatch", DbType:="VarChar(255)")>  _
	Public Property txtPencomBatch() As String
		Get
			Return Me._txtPencomBatch
		End Get
		Set
			If (String.Equals(Me._txtPencomBatch, value) = false) Then
				Me.OntxtPencomBatchChanging(value)
				Me.SendPropertyChanging
				Me._txtPencomBatch = value
				Me.SendPropertyChanged("txtPencomBatch")
				Me.OntxtPencomBatchChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtSPBatchNo", DbType:="VarChar(255)")>  _
	Public Property txtSPBatchNo() As String
		Get
			Return Me._txtSPBatchNo
		End Get
		Set
			If (String.Equals(Me._txtSPBatchNo, value) = false) Then
				If Me._tblSPLog.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OntxtSPBatchNoChanging(value)
				Me.SendPropertyChanging
				Me._txtSPBatchNo = value
				Me.SendPropertyChanged("txtSPBatchNo")
				Me.OntxtSPBatchNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDocumentCompleted", DbType:="DateTime")>  _
	Public Property dteDocumentCompleted() As System.Nullable(Of Date)
		Get
			Return Me._dteDocumentCompleted
		End Get
		Set
			If (Me._dteDocumentCompleted.Equals(value) = false) Then
				Me.OndteDocumentCompletedChanging(value)
				Me.SendPropertyChanging
				Me._dteDocumentCompleted = value
				Me.SendPropertyChanged("dteDocumentCompleted")
				Me.OndteDocumentCompletedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteProcessing", DbType:="DateTime")>  _
	Public Property dteProcessing() As System.Nullable(Of Date)
		Get
			Return Me._dteProcessing
		End Get
		Set
			If (Me._dteProcessing.Equals(value) = false) Then
				Me.OndteProcessingChanging(value)
				Me.SendPropertyChanging
				Me._dteProcessing = value
				Me.SendPropertyChanged("dteProcessing")
				Me.OndteProcessingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteConfirmed", DbType:="DateTime")>  _
	Public Property dteConfirmed() As System.Nullable(Of Date)
		Get
			Return Me._dteConfirmed
		End Get
		Set
			If (Me._dteConfirmed.Equals(value) = false) Then
				Me.OndteConfirmedChanging(value)
				Me.SendPropertyChanging
				Me._dteConfirmed = value
				Me.SendPropertyChanged("dteConfirmed")
				Me.OndteConfirmedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dtePaid", DbType:="DateTime")>  _
	Public Property dtePaid() As System.Nullable(Of Date)
		Get
			Return Me._dtePaid
		End Get
		Set
			If (Me._dtePaid.Equals(value) = false) Then
				Me.OndtePaidChanging(value)
				Me.SendPropertyChanging
				Me._dtePaid = value
				Me.SendPropertyChanged("dtePaid")
				Me.OndtePaidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteApproved", DbType:="DateTime")>  _
	Public Property dteApproved() As System.Nullable(Of Date)
		Get
			Return Me._dteApproved
		End Get
		Set
			If (Me._dteApproved.Equals(value) = false) Then
				Me.OndteApprovedChanging(value)
				Me.SendPropertyChanging
				Me._dteApproved = value
				Me.SendPropertyChanged("dteApproved")
				Me.OndteApprovedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteTerminated", DbType:="DateTime")>  _
	Public Property dteTerminated() As System.Nullable(Of Date)
		Get
			Return Me._dteTerminated
		End Get
		Set
			If (Me._dteTerminated.Equals(value) = false) Then
				Me.OndteTerminatedChanging(value)
				Me.SendPropertyChanging
				Me._dteTerminated = value
				Me.SendPropertyChanged("dteTerminated")
				Me.OndteTerminatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numRSABalance", DbType:="Decimal(18,2)")>  _
	Public Property numRSABalance() As System.Nullable(Of Decimal)
		Get
			Return Me._numRSABalance
		End Get
		Set
			If (Me._numRSABalance.Equals(value) = false) Then
				Me.OnnumRSABalanceChanging(value)
				Me.SendPropertyChanging
				Me._numRSABalance = value
				Me.SendPropertyChanged("numRSABalance")
				Me.OnnumRSABalanceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numLumpSum", DbType:="Decimal(18,2)")>  _
	Public Property numLumpSum() As System.Nullable(Of Decimal)
		Get
			Return Me._numLumpSum
		End Get
		Set
			If (Me._numLumpSum.Equals(value) = false) Then
				Me.OnnumLumpSumChanging(value)
				Me.SendPropertyChanging
				Me._numLumpSum = value
				Me.SendPropertyChanged("numLumpSum")
				Me.OnnumLumpSumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numMonthlyPW", DbType:="Decimal(18,2)")>  _
	Public Property numMonthlyPW() As System.Nullable(Of Decimal)
		Get
			Return Me._numMonthlyPW
		End Get
		Set
			If (Me._numMonthlyPW.Equals(value) = false) Then
				Me.OnnumMonthlyPWChanging(value)
				Me.SendPropertyChanging
				Me._numMonthlyPW = value
				Me.SendPropertyChanged("numMonthlyPW")
				Me.OnnumMonthlyPWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numPremium", DbType:="Decimal(18,2)")>  _
	Public Property numPremium() As System.Nullable(Of Decimal)
		Get
			Return Me._numPremium
		End Get
		Set
			If (Me._numPremium.Equals(value) = false) Then
				Me.OnnumPremiumChanging(value)
				Me.SendPropertyChanging
				Me._numPremium = value
				Me.SendPropertyChanged("numPremium")
				Me.OnnumPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numAnnuity", DbType:="Decimal(18,2)")>  _
	Public Property numAnnuity() As System.Nullable(Of Decimal)
		Get
			Return Me._numAnnuity
		End Get
		Set
			If (Me._numAnnuity.Equals(value) = false) Then
				Me.OnnumAnnuityChanging(value)
				Me.SendPropertyChanging
				Me._numAnnuity = value
				Me.SendPropertyChanged("numAnnuity")
				Me.OnnumAnnuityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteConfirmPriceDate", DbType:="DateTime")>  _
	Public Property dteConfirmPriceDate() As System.Nullable(Of Date)
		Get
			Return Me._dteConfirmPriceDate
		End Get
		Set
			If (Me._dteConfirmPriceDate.Equals(value) = false) Then
				Me.OndteConfirmPriceDateChanging(value)
				Me.SendPropertyChanging
				Me._dteConfirmPriceDate = value
				Me.SendPropertyChanged("dteConfirmPriceDate")
				Me.OndteConfirmPriceDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtReason", DbType:="VarChar(50)")>  _
	Public Property txtReason() As String
		Get
			Return Me._txtReason
		End Get
		Set
			If (String.Equals(Me._txtReason, value) = false) Then
				Me.OntxtReasonChanging(value)
				Me.SendPropertyChanging
				Me._txtReason = value
				Me.SendPropertyChanged("txtReason")
				Me.OntxtReasonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiEmployerID", DbType:="Int")>  _
	Public Property fkiEmployerID() As System.Nullable(Of Integer)
		Get
			Return Me._fkiEmployerID
		End Get
		Set
			If (Me._fkiEmployerID.Equals(value) = false) Then
				Me.OnfkiEmployerIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiEmployerID = value
				Me.SendPropertyChanged("fkiEmployerID")
				Me.OnfkiEmployerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtEmployerCode", DbType:="VarChar(50)")>  _
	Public Property txtEmployerCode() As String
		Get
			Return Me._txtEmployerCode
		End Get
		Set
			If (String.Equals(Me._txtEmployerCode, value) = false) Then
				Me.OntxtEmployerCodeChanging(value)
				Me.SendPropertyChanging
				Me._txtEmployerCode = value
				Me.SendPropertyChanged("txtEmployerCode")
				Me.OntxtEmployerCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtDepartment", DbType:="VarChar(100)")>  _
	Public Property txtDepartment() As String
		Get
			Return Me._txtDepartment
		End Get
		Set
			If (String.Equals(Me._txtDepartment, value) = false) Then
				Me.OntxtDepartmentChanging(value)
				Me.SendPropertyChanging
				Me._txtDepartment = value
				Me.SendPropertyChanged("txtDepartment")
				Me.OntxtDepartmentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtDesignation", DbType:="VarChar(100)")>  _
	Public Property txtDesignation() As String
		Get
			Return Me._txtDesignation
		End Get
		Set
			If (String.Equals(Me._txtDesignation, value) = false) Then
				Me.OntxtDesignationChanging(value)
				Me.SendPropertyChanging
				Me._txtDesignation = value
				Me.SendPropertyChanged("txtDesignation")
				Me.OntxtDesignationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtInsuranceCompany", DbType:="VarChar(300)")>  _
	Public Property txtInsuranceCompany() As String
		Get
			Return Me._txtInsuranceCompany
		End Get
		Set
			If (String.Equals(Me._txtInsuranceCompany, value) = false) Then
				Me.OntxtInsuranceCompanyChanging(value)
				Me.SendPropertyChanging
				Me._txtInsuranceCompany = value
				Me.SendPropertyChanged("txtInsuranceCompany")
				Me.OntxtInsuranceCompanyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtLastChangedPerson", DbType:="VarChar(50)")>  _
	Public Property txtLastChangedPerson() As String
		Get
			Return Me._txtLastChangedPerson
		End Get
		Set
			If (String.Equals(Me._txtLastChangedPerson, value) = false) Then
				Me.OntxtLastChangedPersonChanging(value)
				Me.SendPropertyChanging
				Me._txtLastChangedPerson = value
				Me.SendPropertyChanged("txtLastChangedPerson")
				Me.OntxtLastChangedPersonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtAccountName", DbType:="VarChar(100)")>  _
	Public Property txtAccountName() As String
		Get
			Return Me._txtAccountName
		End Get
		Set
			If (String.Equals(Me._txtAccountName, value) = false) Then
				Me.OntxtAccountNameChanging(value)
				Me.SendPropertyChanging
				Me._txtAccountName = value
				Me.SendPropertyChanged("txtAccountName")
				Me.OntxtAccountNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtAccountNo", DbType:="VarChar(50)")>  _
	Public Property txtAccountNo() As String
		Get
			Return Me._txtAccountNo
		End Get
		Set
			If (String.Equals(Me._txtAccountNo, value) = false) Then
				Me.OntxtAccountNoChanging(value)
				Me.SendPropertyChanging
				Me._txtAccountNo = value
				Me.SendPropertyChanged("txtAccountNo")
				Me.OntxtAccountNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtBVN", DbType:="VarChar(50)")>  _
	Public Property txtBVN() As String
		Get
			Return Me._txtBVN
		End Get
		Set
			If (String.Equals(Me._txtBVN, value) = false) Then
				Me.OntxtBVNChanging(value)
				Me.SendPropertyChanging
				Me._txtBVN = value
				Me.SendPropertyChanged("txtBVN")
				Me.OntxtBVNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiBankID", DbType:="Int")>  _
	Public Property fkiBankID() As System.Nullable(Of Integer)
		Get
			Return Me._fkiBankID
		End Get
		Set
			If (Me._fkiBankID.Equals(value) = false) Then
				Me.OnfkiBankIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiBankID = value
				Me.SendPropertyChanged("fkiBankID")
				Me.OnfkiBankIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiBranchID", DbType:="Int")>  _
	Public Property fkiBranchID() As System.Nullable(Of Integer)
		Get
			Return Me._fkiBranchID
		End Get
		Set
			If (Me._fkiBranchID.Equals(value) = false) Then
				Me.OnfkiBranchIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiBranchID = value
				Me.SendPropertyChanged("fkiBranchID")
				Me.OnfkiBranchIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCommentGroup", DbType:="VarChar(50)")>  _
	Public Property txtCommentGroup() As String
		Get
			Return Me._txtCommentGroup
		End Get
		Set
			If (String.Equals(Me._txtCommentGroup, value) = false) Then
				Me.OntxtCommentGroupChanging(value)
				Me.SendPropertyChanging
				Me._txtCommentGroup = value
				Me.SendPropertyChanged("txtCommentGroup")
				Me.OntxtCommentGroupChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtFundStatus", DbType:="VarChar(20)")>  _
	Public Property txtFundStatus() As String
		Get
			Return Me._txtFundStatus
		End Get
		Set
			If (String.Equals(Me._txtFundStatus, value) = false) Then
				Me.OntxtFundStatusChanging(value)
				Me.SendPropertyChanging
				Me._txtFundStatus = value
				Me.SendPropertyChanged("txtFundStatus")
				Me.OntxtFundStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDeactivated", DbType:="Bit")>  _
	Public Property IsDeactivated() As System.Nullable(Of Boolean)
		Get
			Return Me._IsDeactivated
		End Get
		Set
			If (Me._IsDeactivated.Equals(value) = false) Then
				Me.OnIsDeactivatedChanging(value)
				Me.SendPropertyChanging
				Me._IsDeactivated = value
				Me.SendPropertyChanged("IsDeactivated")
				Me.OnIsDeactivatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDeactivated", DbType:="DateTime")>  _
	Public Property dteDeactivated() As System.Nullable(Of Date)
		Get
			Return Me._dteDeactivated
		End Get
		Set
			If (Me._dteDeactivated.Equals(value) = false) Then
				Me.OndteDeactivatedChanging(value)
				Me.SendPropertyChanging
				Me._dteDeactivated = value
				Me.SendPropertyChanged("dteDeactivated")
				Me.OndteDeactivatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtDeactivatedBy", DbType:="VarChar(20)")>  _
	Public Property txtDeactivatedBy() As String
		Get
			Return Me._txtDeactivatedBy
		End Get
		Set
			If (String.Equals(Me._txtDeactivatedBy, value) = false) Then
				Me.OntxtDeactivatedByChanging(value)
				Me.SendPropertyChanging
				Me._txtDeactivatedBy = value
				Me.SendPropertyChanged("txtDeactivatedBy")
				Me.OntxtDeactivatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblApplicationType_tblMemberApplication", Storage:="_tblApplicationType", ThisKey:="fkiAppTypeId", OtherKey:="pkiAppTypeId", IsForeignKey:=true)>  _
	Public Property tblApplicationType() As tblApplicationType
		Get
			Return Me._tblApplicationType.Entity
		End Get
		Set
			Dim previousValue As tblApplicationType = Me._tblApplicationType.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._tblApplicationType.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._tblApplicationType.Entity = Nothing
					previousValue.tblMemberApplications.Remove(Me)
				End If
				Me._tblApplicationType.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.tblMemberApplications.Add(Me)
					Me._fkiAppTypeId = value.pkiAppTypeId
				Else
					Me._fkiAppTypeId = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("tblApplicationType")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblSPLog_tblMemberApplication", Storage:="_tblSPLog", ThisKey:="txtSPBatchNo", OtherKey:="txtBatchNo", IsForeignKey:=true)>  _
	Public Property tblSPLog() As tblSPLog
		Get
			Return Me._tblSPLog.Entity
		End Get
		Set
			Dim previousValue As tblSPLog = Me._tblSPLog.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._tblSPLog.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._tblSPLog.Entity = Nothing
					previousValue.tblMemberApplications.Remove(Me)
				End If
				Me._tblSPLog.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.tblMemberApplications.Add(Me)
					Me._txtSPBatchNo = value.txtBatchNo
				Else
					Me._txtSPBatchNo = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("tblSPLog")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblSPLog")>  _
Partial Public Class tblSPLog
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _intSPLog As Integer
	
	Private _txtBatchNo As String
	
	Private _dteGenerated As System.Nullable(Of Date)
	
	Private _fkiAppTypeId As System.Nullable(Of Integer)
	
	Private _txtCreatedBy As String
	
	Private _tblMemberApplications As EntitySet(Of tblMemberApplication)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnintSPLogChanging(value As Integer)
    End Sub
    Partial Private Sub OnintSPLogChanged()
    End Sub
    Partial Private Sub OntxtBatchNoChanging(value As String)
    End Sub
    Partial Private Sub OntxtBatchNoChanged()
    End Sub
    Partial Private Sub OndteGeneratedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteGeneratedChanged()
    End Sub
    Partial Private Sub OnfkiAppTypeIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfkiAppTypeIdChanged()
    End Sub
    Partial Private Sub OntxtCreatedByChanging(value As String)
    End Sub
    Partial Private Sub OntxtCreatedByChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblMemberApplications = New EntitySet(Of tblMemberApplication)(AddressOf Me.attach_tblMemberApplications, AddressOf Me.detach_tblMemberApplications)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_intSPLog", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property intSPLog() As Integer
		Get
			Return Me._intSPLog
		End Get
		Set
			If ((Me._intSPLog = value)  _
						= false) Then
				Me.OnintSPLogChanging(value)
				Me.SendPropertyChanging
				Me._intSPLog = value
				Me.SendPropertyChanged("intSPLog")
				Me.OnintSPLogChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtBatchNo", DbType:="VarChar(255)")>  _
	Public Property txtBatchNo() As String
		Get
			Return Me._txtBatchNo
		End Get
		Set
			If (String.Equals(Me._txtBatchNo, value) = false) Then
				Me.OntxtBatchNoChanging(value)
				Me.SendPropertyChanging
				Me._txtBatchNo = value
				Me.SendPropertyChanged("txtBatchNo")
				Me.OntxtBatchNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteGenerated", DbType:="DateTime")>  _
	Public Property dteGenerated() As System.Nullable(Of Date)
		Get
			Return Me._dteGenerated
		End Get
		Set
			If (Me._dteGenerated.Equals(value) = false) Then
				Me.OndteGeneratedChanging(value)
				Me.SendPropertyChanging
				Me._dteGenerated = value
				Me.SendPropertyChanged("dteGenerated")
				Me.OndteGeneratedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiAppTypeId", DbType:="Int")>  _
	Public Property fkiAppTypeId() As System.Nullable(Of Integer)
		Get
			Return Me._fkiAppTypeId
		End Get
		Set
			If (Me._fkiAppTypeId.Equals(value) = false) Then
				Me.OnfkiAppTypeIdChanging(value)
				Me.SendPropertyChanging
				Me._fkiAppTypeId = value
				Me.SendPropertyChanged("fkiAppTypeId")
				Me.OnfkiAppTypeIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCreatedBy", DbType:="VarChar(20)")>  _
	Public Property txtCreatedBy() As String
		Get
			Return Me._txtCreatedBy
		End Get
		Set
			If (String.Equals(Me._txtCreatedBy, value) = false) Then
				Me.OntxtCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._txtCreatedBy = value
				Me.SendPropertyChanged("txtCreatedBy")
				Me.OntxtCreatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblSPLog_tblMemberApplication", Storage:="_tblMemberApplications", ThisKey:="txtBatchNo", OtherKey:="txtSPBatchNo")>  _
	Public Property tblMemberApplications() As EntitySet(Of tblMemberApplication)
		Get
			Return Me._tblMemberApplications
		End Get
		Set
			Me._tblMemberApplications.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_tblMemberApplications(ByVal entity As tblMemberApplication)
		Me.SendPropertyChanging
		entity.tblSPLog = Me
	End Sub
	
	Private Sub detach_tblMemberApplications(ByVal entity As tblMemberApplication)
		Me.SendPropertyChanging
		entity.tblSPLog = Nothing
	End Sub
End Class
