'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="EnPowerV4")>  _
Partial Public Class BanksDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertBank(instance As Bank)
    End Sub
  Partial Private Sub UpdateBank(instance As Bank)
    End Sub
  Partial Private Sub DeleteBank(instance As Bank)
    End Sub
  Partial Private Sub InsertBankBranch(instance As BankBranch)
    End Sub
  Partial Private Sub UpdateBankBranch(instance As BankBranch)
    End Sub
  Partial Private Sub DeleteBankBranch(instance As BankBranch)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("EnPowerV4ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Banks() As System.Data.Linq.Table(Of Bank)
		Get
			Return Me.GetTable(Of Bank)
		End Get
	End Property
	
	Public ReadOnly Property BankBranches() As System.Data.Linq.Table(Of BankBranch)
		Get
			Return Me.GetTable(Of BankBranch)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Bank")>  _
Partial Public Class Bank
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _BankID As Integer
	
	Private _BankName As String
	
	Private _DateCreated As Date
	
	Private _CreatedByID As Integer
	
	Private _DateModified As System.Nullable(Of Date)
	
	Private _ModifiedByID As System.Nullable(Of Integer)
	
	Private _IsArchived As Boolean
	
	Private _BankBranches As EntitySet(Of BankBranch)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnBankIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnBankIDChanged()
    End Sub
    Partial Private Sub OnBankNameChanging(value As String)
    End Sub
    Partial Private Sub OnBankNameChanged()
    End Sub
    Partial Private Sub OnDateCreatedChanging(value As Date)
    End Sub
    Partial Private Sub OnDateCreatedChanged()
    End Sub
    Partial Private Sub OnCreatedByIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCreatedByIDChanged()
    End Sub
    Partial Private Sub OnDateModifiedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateModifiedChanged()
    End Sub
    Partial Private Sub OnModifiedByIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnModifiedByIDChanged()
    End Sub
    Partial Private Sub OnIsArchivedChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsArchivedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._BankBranches = New EntitySet(Of BankBranch)(AddressOf Me.attach_BankBranches, AddressOf Me.detach_BankBranches)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property BankID() As Integer
		Get
			Return Me._BankID
		End Get
		Set
			If ((Me._BankID = value)  _
						= false) Then
				Me.OnBankIDChanging(value)
				Me.SendPropertyChanging
				Me._BankID = value
				Me.SendPropertyChanged("BankID")
				Me.OnBankIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankName", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property BankName() As String
		Get
			Return Me._BankName
		End Get
		Set
			If (String.Equals(Me._BankName, value) = false) Then
				Me.OnBankNameChanging(value)
				Me.SendPropertyChanging
				Me._BankName = value
				Me.SendPropertyChanged("BankName")
				Me.OnBankNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreated", DbType:="DateTime NOT NULL")>  _
	Public Property DateCreated() As Date
		Get
			Return Me._DateCreated
		End Get
		Set
			If ((Me._DateCreated = value)  _
						= false) Then
				Me.OnDateCreatedChanging(value)
				Me.SendPropertyChanging
				Me._DateCreated = value
				Me.SendPropertyChanged("DateCreated")
				Me.OnDateCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedByID", DbType:="Int NOT NULL")>  _
	Public Property CreatedByID() As Integer
		Get
			Return Me._CreatedByID
		End Get
		Set
			If ((Me._CreatedByID = value)  _
						= false) Then
				Me.OnCreatedByIDChanging(value)
				Me.SendPropertyChanging
				Me._CreatedByID = value
				Me.SendPropertyChanged("CreatedByID")
				Me.OnCreatedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateModified", DbType:="DateTime")>  _
	Public Property DateModified() As System.Nullable(Of Date)
		Get
			Return Me._DateModified
		End Get
		Set
			If (Me._DateModified.Equals(value) = false) Then
				Me.OnDateModifiedChanging(value)
				Me.SendPropertyChanging
				Me._DateModified = value
				Me.SendPropertyChanged("DateModified")
				Me.OnDateModifiedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModifiedByID", DbType:="Int")>  _
	Public Property ModifiedByID() As System.Nullable(Of Integer)
		Get
			Return Me._ModifiedByID
		End Get
		Set
			If (Me._ModifiedByID.Equals(value) = false) Then
				Me.OnModifiedByIDChanging(value)
				Me.SendPropertyChanging
				Me._ModifiedByID = value
				Me.SendPropertyChanged("ModifiedByID")
				Me.OnModifiedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsArchived", DbType:="Bit NOT NULL")>  _
	Public Property IsArchived() As Boolean
		Get
			Return Me._IsArchived
		End Get
		Set
			If ((Me._IsArchived = value)  _
						= false) Then
				Me.OnIsArchivedChanging(value)
				Me.SendPropertyChanging
				Me._IsArchived = value
				Me.SendPropertyChanged("IsArchived")
				Me.OnIsArchivedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Bank_BankBranch", Storage:="_BankBranches", ThisKey:="BankID", OtherKey:="BankID")>  _
	Public Property BankBranches() As EntitySet(Of BankBranch)
		Get
			Return Me._BankBranches
		End Get
		Set
			Me._BankBranches.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_BankBranches(ByVal entity As BankBranch)
		Me.SendPropertyChanging
		entity.Bank = Me
	End Sub
	
	Private Sub detach_BankBranches(ByVal entity As BankBranch)
		Me.SendPropertyChanging
		entity.Bank = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.BankBranch")>  _
Partial Public Class BankBranch
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _BankBranchID As Integer
	
	Private _BranchName As String
	
	Private _SortCode As String
	
	Private _BankID As System.Nullable(Of Integer)
	
	Private _BranchStateID As Integer
	
	Private _DateCreated As Date
	
	Private _CreatedByID As Integer
	
	Private _DateModified As System.Nullable(Of Date)
	
	Private _ModifiedByID As System.Nullable(Of Integer)
	
	Private _IsArchived As System.Nullable(Of Boolean)
	
	Private _Bank As EntityRef(Of Bank)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnBankBranchIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnBankBranchIDChanged()
    End Sub
    Partial Private Sub OnBranchNameChanging(value As String)
    End Sub
    Partial Private Sub OnBranchNameChanged()
    End Sub
    Partial Private Sub OnSortCodeChanging(value As String)
    End Sub
    Partial Private Sub OnSortCodeChanged()
    End Sub
    Partial Private Sub OnBankIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBankIDChanged()
    End Sub
    Partial Private Sub OnBranchStateIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnBranchStateIDChanged()
    End Sub
    Partial Private Sub OnDateCreatedChanging(value As Date)
    End Sub
    Partial Private Sub OnDateCreatedChanged()
    End Sub
    Partial Private Sub OnCreatedByIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCreatedByIDChanged()
    End Sub
    Partial Private Sub OnDateModifiedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateModifiedChanged()
    End Sub
    Partial Private Sub OnModifiedByIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnModifiedByIDChanged()
    End Sub
    Partial Private Sub OnIsArchivedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsArchivedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._Bank = CType(Nothing, EntityRef(Of Bank))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankBranchID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property BankBranchID() As Integer
		Get
			Return Me._BankBranchID
		End Get
		Set
			If ((Me._BankBranchID = value)  _
						= false) Then
				Me.OnBankBranchIDChanging(value)
				Me.SendPropertyChanging
				Me._BankBranchID = value
				Me.SendPropertyChanged("BankBranchID")
				Me.OnBankBranchIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BranchName", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property BranchName() As String
		Get
			Return Me._BranchName
		End Get
		Set
			If (String.Equals(Me._BranchName, value) = false) Then
				Me.OnBranchNameChanging(value)
				Me.SendPropertyChanging
				Me._BranchName = value
				Me.SendPropertyChanged("BranchName")
				Me.OnBranchNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SortCode", DbType:="VarChar(50)")>  _
	Public Property SortCode() As String
		Get
			Return Me._SortCode
		End Get
		Set
			If (String.Equals(Me._SortCode, value) = false) Then
				Me.OnSortCodeChanging(value)
				Me.SendPropertyChanging
				Me._SortCode = value
				Me.SendPropertyChanged("SortCode")
				Me.OnSortCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankID", DbType:="Int")>  _
	Public Property BankID() As System.Nullable(Of Integer)
		Get
			Return Me._BankID
		End Get
		Set
			If (Me._BankID.Equals(value) = false) Then
				If Me._Bank.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnBankIDChanging(value)
				Me.SendPropertyChanging
				Me._BankID = value
				Me.SendPropertyChanged("BankID")
				Me.OnBankIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BranchStateID", DbType:="Int NOT NULL")>  _
	Public Property BranchStateID() As Integer
		Get
			Return Me._BranchStateID
		End Get
		Set
			If ((Me._BranchStateID = value)  _
						= false) Then
				Me.OnBranchStateIDChanging(value)
				Me.SendPropertyChanging
				Me._BranchStateID = value
				Me.SendPropertyChanged("BranchStateID")
				Me.OnBranchStateIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreated", DbType:="DateTime NOT NULL")>  _
	Public Property DateCreated() As Date
		Get
			Return Me._DateCreated
		End Get
		Set
			If ((Me._DateCreated = value)  _
						= false) Then
				Me.OnDateCreatedChanging(value)
				Me.SendPropertyChanging
				Me._DateCreated = value
				Me.SendPropertyChanged("DateCreated")
				Me.OnDateCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedByID", DbType:="Int NOT NULL")>  _
	Public Property CreatedByID() As Integer
		Get
			Return Me._CreatedByID
		End Get
		Set
			If ((Me._CreatedByID = value)  _
						= false) Then
				Me.OnCreatedByIDChanging(value)
				Me.SendPropertyChanging
				Me._CreatedByID = value
				Me.SendPropertyChanged("CreatedByID")
				Me.OnCreatedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateModified", DbType:="DateTime")>  _
	Public Property DateModified() As System.Nullable(Of Date)
		Get
			Return Me._DateModified
		End Get
		Set
			If (Me._DateModified.Equals(value) = false) Then
				Me.OnDateModifiedChanging(value)
				Me.SendPropertyChanging
				Me._DateModified = value
				Me.SendPropertyChanged("DateModified")
				Me.OnDateModifiedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModifiedByID", DbType:="Int")>  _
	Public Property ModifiedByID() As System.Nullable(Of Integer)
		Get
			Return Me._ModifiedByID
		End Get
		Set
			If (Me._ModifiedByID.Equals(value) = false) Then
				Me.OnModifiedByIDChanging(value)
				Me.SendPropertyChanging
				Me._ModifiedByID = value
				Me.SendPropertyChanged("ModifiedByID")
				Me.OnModifiedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsArchived", DbType:="Bit")>  _
	Public Property IsArchived() As System.Nullable(Of Boolean)
		Get
			Return Me._IsArchived
		End Get
		Set
			If (Me._IsArchived.Equals(value) = false) Then
				Me.OnIsArchivedChanging(value)
				Me.SendPropertyChanging
				Me._IsArchived = value
				Me.SendPropertyChanged("IsArchived")
				Me.OnIsArchivedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Bank_BankBranch", Storage:="_Bank", ThisKey:="BankID", OtherKey:="BankID", IsForeignKey:=true)>  _
	Public Property Bank() As Bank
		Get
			Return Me._Bank.Entity
		End Get
		Set
			Dim previousValue As Bank = Me._Bank.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._Bank.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._Bank.Entity = Nothing
					previousValue.BankBranches.Remove(Me)
				End If
				Me._Bank.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.BankBranches.Add(Me)
					Me._BankID = value.BankID
				Else
					Me._BankID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("Bank")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
