'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="EnPowerV4")>  _
Partial Public Class InsurerDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertInsurer(instance As Insurer)
    End Sub
  Partial Private Sub UpdateInsurer(instance As Insurer)
    End Sub
  Partial Private Sub DeleteInsurer(instance As Insurer)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("EnPowerV4ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Insurers() As System.Data.Linq.Table(Of Insurer)
		Get
			Return Me.GetTable(Of Insurer)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Insurer")>  _
Partial Public Class Insurer
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _InsurerID As Integer
	
	Private _InsurerName As String
	
	Private _InsurerCode As String
	
	Private _InsurerAddress As String
	
	Private _InsurerPhone As String
	
	Private _InsurerContactPerson As String
	
	Private _BankName As String
	
	Private _AccountNumber As String
	
	Private _DateCreated As Date
	
	Private _CreatedByID As Integer
	
	Private _DateModified As System.Nullable(Of Date)
	
	Private _ModifiedByID As System.Nullable(Of Integer)
	
	Private _IsArchived As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnInsurerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnInsurerIDChanged()
    End Sub
    Partial Private Sub OnInsurerNameChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerNameChanged()
    End Sub
    Partial Private Sub OnInsurerCodeChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerCodeChanged()
    End Sub
    Partial Private Sub OnInsurerAddressChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerAddressChanged()
    End Sub
    Partial Private Sub OnInsurerPhoneChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerPhoneChanged()
    End Sub
    Partial Private Sub OnInsurerContactPersonChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerContactPersonChanged()
    End Sub
    Partial Private Sub OnBankNameChanging(value As String)
    End Sub
    Partial Private Sub OnBankNameChanged()
    End Sub
    Partial Private Sub OnAccountNumberChanging(value As String)
    End Sub
    Partial Private Sub OnAccountNumberChanged()
    End Sub
    Partial Private Sub OnDateCreatedChanging(value As Date)
    End Sub
    Partial Private Sub OnDateCreatedChanged()
    End Sub
    Partial Private Sub OnCreatedByIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCreatedByIDChanged()
    End Sub
    Partial Private Sub OnDateModifiedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateModifiedChanged()
    End Sub
    Partial Private Sub OnModifiedByIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnModifiedByIDChanged()
    End Sub
    Partial Private Sub OnIsArchivedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsArchivedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property InsurerID() As Integer
		Get
			Return Me._InsurerID
		End Get
		Set
			If ((Me._InsurerID = value)  _
						= false) Then
				Me.OnInsurerIDChanging(value)
				Me.SendPropertyChanging
				Me._InsurerID = value
				Me.SendPropertyChanged("InsurerID")
				Me.OnInsurerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerName", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property InsurerName() As String
		Get
			Return Me._InsurerName
		End Get
		Set
			If (String.Equals(Me._InsurerName, value) = false) Then
				Me.OnInsurerNameChanging(value)
				Me.SendPropertyChanging
				Me._InsurerName = value
				Me.SendPropertyChanged("InsurerName")
				Me.OnInsurerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerCode", DbType:="VarChar(20)")>  _
	Public Property InsurerCode() As String
		Get
			Return Me._InsurerCode
		End Get
		Set
			If (String.Equals(Me._InsurerCode, value) = false) Then
				Me.OnInsurerCodeChanging(value)
				Me.SendPropertyChanging
				Me._InsurerCode = value
				Me.SendPropertyChanged("InsurerCode")
				Me.OnInsurerCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerAddress", DbType:="VarChar(250)")>  _
	Public Property InsurerAddress() As String
		Get
			Return Me._InsurerAddress
		End Get
		Set
			If (String.Equals(Me._InsurerAddress, value) = false) Then
				Me.OnInsurerAddressChanging(value)
				Me.SendPropertyChanging
				Me._InsurerAddress = value
				Me.SendPropertyChanged("InsurerAddress")
				Me.OnInsurerAddressChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerPhone", DbType:="VarChar(20)")>  _
	Public Property InsurerPhone() As String
		Get
			Return Me._InsurerPhone
		End Get
		Set
			If (String.Equals(Me._InsurerPhone, value) = false) Then
				Me.OnInsurerPhoneChanging(value)
				Me.SendPropertyChanging
				Me._InsurerPhone = value
				Me.SendPropertyChanged("InsurerPhone")
				Me.OnInsurerPhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerContactPerson", DbType:="VarChar(20)")>  _
	Public Property InsurerContactPerson() As String
		Get
			Return Me._InsurerContactPerson
		End Get
		Set
			If (String.Equals(Me._InsurerContactPerson, value) = false) Then
				Me.OnInsurerContactPersonChanging(value)
				Me.SendPropertyChanging
				Me._InsurerContactPerson = value
				Me.SendPropertyChanged("InsurerContactPerson")
				Me.OnInsurerContactPersonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankName", DbType:="VarChar(50)")>  _
	Public Property BankName() As String
		Get
			Return Me._BankName
		End Get
		Set
			If (String.Equals(Me._BankName, value) = false) Then
				Me.OnBankNameChanging(value)
				Me.SendPropertyChanging
				Me._BankName = value
				Me.SendPropertyChanged("BankName")
				Me.OnBankNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountNumber", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property AccountNumber() As String
		Get
			Return Me._AccountNumber
		End Get
		Set
			If (String.Equals(Me._AccountNumber, value) = false) Then
				Me.OnAccountNumberChanging(value)
				Me.SendPropertyChanging
				Me._AccountNumber = value
				Me.SendPropertyChanged("AccountNumber")
				Me.OnAccountNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreated", DbType:="DateTime NOT NULL")>  _
	Public Property DateCreated() As Date
		Get
			Return Me._DateCreated
		End Get
		Set
			If ((Me._DateCreated = value)  _
						= false) Then
				Me.OnDateCreatedChanging(value)
				Me.SendPropertyChanging
				Me._DateCreated = value
				Me.SendPropertyChanged("DateCreated")
				Me.OnDateCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedByID", DbType:="Int NOT NULL")>  _
	Public Property CreatedByID() As Integer
		Get
			Return Me._CreatedByID
		End Get
		Set
			If ((Me._CreatedByID = value)  _
						= false) Then
				Me.OnCreatedByIDChanging(value)
				Me.SendPropertyChanging
				Me._CreatedByID = value
				Me.SendPropertyChanged("CreatedByID")
				Me.OnCreatedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateModified", DbType:="DateTime")>  _
	Public Property DateModified() As System.Nullable(Of Date)
		Get
			Return Me._DateModified
		End Get
		Set
			If (Me._DateModified.Equals(value) = false) Then
				Me.OnDateModifiedChanging(value)
				Me.SendPropertyChanging
				Me._DateModified = value
				Me.SendPropertyChanged("DateModified")
				Me.OnDateModifiedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModifiedByID", DbType:="Int")>  _
	Public Property ModifiedByID() As System.Nullable(Of Integer)
		Get
			Return Me._ModifiedByID
		End Get
		Set
			If (Me._ModifiedByID.Equals(value) = false) Then
				Me.OnModifiedByIDChanging(value)
				Me.SendPropertyChanging
				Me._ModifiedByID = value
				Me.SendPropertyChanged("ModifiedByID")
				Me.OnModifiedByIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsArchived", DbType:="Bit")>  _
	Public Property IsArchived() As System.Nullable(Of Boolean)
		Get
			Return Me._IsArchived
		End Get
		Set
			If (Me._IsArchived.Equals(value) = false) Then
				Me.OnIsArchivedChanging(value)
				Me.SendPropertyChanging
				Me._IsArchived = value
				Me.SendPropertyChanged("IsArchived")
				Me.OnIsArchivedChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
