'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8670
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace com.sms.test
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="swsinfoportBinding", [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Partial Public Class swsinfo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private allpricesOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12
            Me.Url = "http://b-appserv:18080/swsinfo/swsinfoport"
        End Sub
        
        '''<remarks/>
        Public Event allpricesCompleted As allpricesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("retrieve_prices", RequestNamespace:="http://com.leadway_pensure.m/ws/all/", ResponseNamespace:="http://com.leadway_pensure.m/ws/all/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function allprices(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal fund As allpricesFund, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal fundSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal range As allpricesRange, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal rangeSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("priceresponse", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> allpricesResponsePriceresponse
            Dim results() As Object = Me.Invoke("allprices", New Object() {fund, fundSpecified, range, rangeSpecified})
            Return CType(results(0),allpricesResponsePriceresponse)
        End Function
        
        '''<remarks/>
        Public Function Beginallprices(ByVal fund As allpricesFund, ByVal fundSpecified As Boolean, ByVal range As allpricesRange, ByVal rangeSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("allprices", New Object() {fund, fundSpecified, range, rangeSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endallprices(ByVal asyncResult As System.IAsyncResult) As allpricesResponsePriceresponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),allpricesResponsePriceresponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub allpricesAsync(ByVal fund As allpricesFund, ByVal fundSpecified As Boolean, ByVal range As allpricesRange, ByVal rangeSpecified As Boolean)
            Me.allpricesAsync(fund, fundSpecified, range, rangeSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub allpricesAsync(ByVal fund As allpricesFund, ByVal fundSpecified As Boolean, ByVal range As allpricesRange, ByVal rangeSpecified As Boolean, ByVal userState As Object)
            If (Me.allpricesOperationCompleted Is Nothing) Then
                Me.allpricesOperationCompleted = AddressOf Me.OnallpricesOperationCompleted
            End If
            Me.InvokeAsync("allprices", New Object() {fund, fundSpecified, range, rangeSpecified}, Me.allpricesOperationCompleted, userState)
        End Sub
        
        Private Sub OnallpricesOperationCompleted(ByVal arg As Object)
            If (Not (Me.allpricesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent allpricesCompleted(Me, New allpricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Public Enum allpricesFund
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("RSA Fund")>  _
        RSAFund
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Retiree Fund")>  _
        RetireeFund
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Guiness Gratuity Fund")>  _
        GuinessGratuityFund
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Public Enum allpricesRange
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last Available Date")>  _
        LastAvailableDate
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Year To Date")>  _
        YearToDate
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 14 Days")>  _
        Last14Days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 1 Month")>  _
        Last1Month
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 3 Months")>  _
        Last3Months
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 1 Year")>  _
        Last1Year
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 5 Years")>  _
        Last5Years
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Partial Public Class allpricesResponsePriceresponse
        
        Private fundinfoField As allpricesResponsePriceresponseFundinfo
        
        Private fundinfoFieldSpecified As Boolean
        
        Private rangeinfoField As allpricesResponsePriceresponseRangeinfo
        
        Private rangeinfoFieldSpecified As Boolean
        
        Private priceinfoField() As allpricesResponsePriceresponsePriceinfo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fundinfo() As allpricesResponsePriceresponseFundinfo
            Get
                Return Me.fundinfoField
            End Get
            Set
                Me.fundinfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fundinfoSpecified() As Boolean
            Get
                Return Me.fundinfoFieldSpecified
            End Get
            Set
                Me.fundinfoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rangeinfo() As allpricesResponsePriceresponseRangeinfo
            Get
                Return Me.rangeinfoField
            End Get
            Set
                Me.rangeinfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property rangeinfoSpecified() As Boolean
            Get
                Return Me.rangeinfoFieldSpecified
            End Get
            Set
                Me.rangeinfoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("priceinfo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property priceinfo() As allpricesResponsePriceresponsePriceinfo()
            Get
                Return Me.priceinfoField
            End Get
            Set
                Me.priceinfoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Public Enum allpricesResponsePriceresponseFundinfo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("RSA Fund")>  _
        RSAFund
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Retiree Fund")>  _
        RetireeFund
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Guiness Gratuity Fund")>  _
        GuinessGratuityFund
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Public Enum allpricesResponsePriceresponseRangeinfo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last Available Date")>  _
        LastAvailableDate
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Year To Date")>  _
        YearToDate
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 14 Days")>  _
        Last14Days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 1 Month")>  _
        Last1Month
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 3 Months")>  _
        Last3Months
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 1 Year")>  _
        Last1Year
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Last 5 Years")>  _
        Last5Years
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://com.leadway_pensure.m/ws/all/")>  _
    Partial Public Class allpricesResponsePriceresponsePriceinfo
        
        Private valuedateField As Date
        
        Private valuedateFieldSpecified As Boolean
        
        Private pricevalueField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property valuedate() As Date
            Get
                Return Me.valuedateField
            End Get
            Set
                Me.valuedateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valuedateSpecified() As Boolean
            Get
                Return Me.valuedateFieldSpecified
            End Get
            Set
                Me.valuedateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property pricevalue() As Double
            Get
                Return Me.pricevalueField
            End Get
            Set
                Me.pricevalueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub allpricesCompletedEventHandler(ByVal sender As Object, ByVal e As allpricesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class allpricesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As allpricesResponsePriceresponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),allpricesResponsePriceresponse)
            End Get
        End Property
    End Class
End Namespace
