'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PaymentModule_femi")>  _
Partial Public Class UsersDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InserttblUser(instance As tblUser)
    End Sub
  Partial Private Sub UpdatetblUser(instance As tblUser)
    End Sub
  Partial Private Sub DeletetblUser(instance As tblUser)
    End Sub
  Partial Private Sub InserttblModule(instance As tblModule)
    End Sub
  Partial Private Sub UpdatetblModule(instance As tblModule)
    End Sub
  Partial Private Sub DeletetblModule(instance As tblModule)
    End Sub
  Partial Private Sub InserttblRole(instance As tblRole)
    End Sub
  Partial Private Sub UpdatetblRole(instance As tblRole)
    End Sub
  Partial Private Sub DeletetblRole(instance As tblRole)
    End Sub
  Partial Private Sub InserttblMLAccess(instance As tblMLAccess)
    End Sub
  Partial Private Sub UpdatetblMLAccess(instance As tblMLAccess)
    End Sub
  Partial Private Sub DeletetblMLAccess(instance As tblMLAccess)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("PaymentModuleConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tblUsers() As System.Data.Linq.Table(Of tblUser)
		Get
			Return Me.GetTable(Of tblUser)
		End Get
	End Property
	
	Public ReadOnly Property tblModules() As System.Data.Linq.Table(Of tblModule)
		Get
			Return Me.GetTable(Of tblModule)
		End Get
	End Property
	
	Public ReadOnly Property tblRoles() As System.Data.Linq.Table(Of tblRole)
		Get
			Return Me.GetTable(Of tblRole)
		End Get
	End Property
	
	Public ReadOnly Property tblMLAccesses() As System.Data.Linq.Table(Of tblMLAccess)
		Get
			Return Me.GetTable(Of tblMLAccess)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblUsers")>  _
Partial Public Class tblUser
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _UserID As Integer
	
	Private _UserName As String
	
	Private _AccessLevel As System.Nullable(Of Integer)
	
	Private _AccessStatus As System.Nullable(Of Integer)
	
	Private _fkiRoleID As System.Nullable(Of Integer)
	
	Private _FullName As String
	
	Private _dteCreated As System.Nullable(Of Date)
	
	Private _IsActive As System.Nullable(Of Boolean)
	
	Private _tblRole As EntityRef(Of tblRole)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnUserIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnUserIDChanged()
    End Sub
    Partial Private Sub OnUserNameChanging(value As String)
    End Sub
    Partial Private Sub OnUserNameChanged()
    End Sub
    Partial Private Sub OnAccessLevelChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnAccessLevelChanged()
    End Sub
    Partial Private Sub OnAccessStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnAccessStatusChanged()
    End Sub
    Partial Private Sub OnfkiRoleIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfkiRoleIDChanged()
    End Sub
    Partial Private Sub OnFullNameChanging(value As String)
    End Sub
    Partial Private Sub OnFullNameChanged()
    End Sub
    Partial Private Sub OndteCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteCreatedChanged()
    End Sub
    Partial Private Sub OnIsActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsActiveChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblRole = CType(Nothing, EntityRef(Of tblRole))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property UserID() As Integer
		Get
			Return Me._UserID
		End Get
		Set
			If ((Me._UserID = value)  _
						= false) Then
				Me.OnUserIDChanging(value)
				Me.SendPropertyChanging
				Me._UserID = value
				Me.SendPropertyChanged("UserID")
				Me.OnUserIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserName", DbType:="VarChar(50)")>  _
	Public Property UserName() As String
		Get
			Return Me._UserName
		End Get
		Set
			If (String.Equals(Me._UserName, value) = false) Then
				Me.OnUserNameChanging(value)
				Me.SendPropertyChanging
				Me._UserName = value
				Me.SendPropertyChanged("UserName")
				Me.OnUserNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccessLevel", DbType:="Int")>  _
	Public Property AccessLevel() As System.Nullable(Of Integer)
		Get
			Return Me._AccessLevel
		End Get
		Set
			If (Me._AccessLevel.Equals(value) = false) Then
				Me.OnAccessLevelChanging(value)
				Me.SendPropertyChanging
				Me._AccessLevel = value
				Me.SendPropertyChanged("AccessLevel")
				Me.OnAccessLevelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccessStatus", DbType:="Int")>  _
	Public Property AccessStatus() As System.Nullable(Of Integer)
		Get
			Return Me._AccessStatus
		End Get
		Set
			If (Me._AccessStatus.Equals(value) = false) Then
				Me.OnAccessStatusChanging(value)
				Me.SendPropertyChanging
				Me._AccessStatus = value
				Me.SendPropertyChanged("AccessStatus")
				Me.OnAccessStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiRoleID", DbType:="Int")>  _
	Public Property fkiRoleID() As System.Nullable(Of Integer)
		Get
			Return Me._fkiRoleID
		End Get
		Set
			If (Me._fkiRoleID.Equals(value) = false) Then
				If Me._tblRole.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnfkiRoleIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiRoleID = value
				Me.SendPropertyChanged("fkiRoleID")
				Me.OnfkiRoleIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullName", DbType:="VarChar(255)")>  _
	Public Property FullName() As String
		Get
			Return Me._FullName
		End Get
		Set
			If (String.Equals(Me._FullName, value) = false) Then
				Me.OnFullNameChanging(value)
				Me.SendPropertyChanging
				Me._FullName = value
				Me.SendPropertyChanged("FullName")
				Me.OnFullNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteCreated", DbType:="DateTime")>  _
	Public Property dteCreated() As System.Nullable(Of Date)
		Get
			Return Me._dteCreated
		End Get
		Set
			If (Me._dteCreated.Equals(value) = false) Then
				Me.OndteCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dteCreated = value
				Me.SendPropertyChanged("dteCreated")
				Me.OndteCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsActive", DbType:="Bit")>  _
	Public Property IsActive() As System.Nullable(Of Boolean)
		Get
			Return Me._IsActive
		End Get
		Set
			If (Me._IsActive.Equals(value) = false) Then
				Me.OnIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._IsActive = value
				Me.SendPropertyChanged("IsActive")
				Me.OnIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblRole_tblUser", Storage:="_tblRole", ThisKey:="fkiRoleID", OtherKey:="pkiRoleID", IsForeignKey:=true)>  _
	Public Property tblRole() As tblRole
		Get
			Return Me._tblRole.Entity
		End Get
		Set
			Dim previousValue As tblRole = Me._tblRole.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._tblRole.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._tblRole.Entity = Nothing
					previousValue.tblUsers.Remove(Me)
				End If
				Me._tblRole.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.tblUsers.Add(Me)
					Me._fkiRoleID = value.pkiRoleID
				Else
					Me._fkiRoleID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("tblRole")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblModules")>  _
Partial Public Class tblModule
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiModuleID As Integer
	
	Private _txtModule As String
	
	Private _txtCreator As String
	
	Private _dteCreated As System.Nullable(Of Date)
	
	Private _txtModuleType As String
	
	Private _isActive As System.Nullable(Of Boolean)
	
	Private _tblMLAccesses As EntitySet(Of tblMLAccess)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiModuleIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiModuleIDChanged()
    End Sub
    Partial Private Sub OntxtModuleChanging(value As String)
    End Sub
    Partial Private Sub OntxtModuleChanged()
    End Sub
    Partial Private Sub OntxtCreatorChanging(value As String)
    End Sub
    Partial Private Sub OntxtCreatorChanged()
    End Sub
    Partial Private Sub OndteCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteCreatedChanged()
    End Sub
    Partial Private Sub OntxtModuleTypeChanging(value As String)
    End Sub
    Partial Private Sub OntxtModuleTypeChanged()
    End Sub
    Partial Private Sub OnisActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisActiveChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblMLAccesses = New EntitySet(Of tblMLAccess)(AddressOf Me.attach_tblMLAccesses, AddressOf Me.detach_tblMLAccesses)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiModuleID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property pkiModuleID() As Integer
		Get
			Return Me._pkiModuleID
		End Get
		Set
			If ((Me._pkiModuleID = value)  _
						= false) Then
				Me.OnpkiModuleIDChanging(value)
				Me.SendPropertyChanging
				Me._pkiModuleID = value
				Me.SendPropertyChanged("pkiModuleID")
				Me.OnpkiModuleIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtModule", DbType:="VarChar(50)")>  _
	Public Property txtModule() As String
		Get
			Return Me._txtModule
		End Get
		Set
			If (String.Equals(Me._txtModule, value) = false) Then
				Me.OntxtModuleChanging(value)
				Me.SendPropertyChanging
				Me._txtModule = value
				Me.SendPropertyChanged("txtModule")
				Me.OntxtModuleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCreator", DbType:="VarChar(50)")>  _
	Public Property txtCreator() As String
		Get
			Return Me._txtCreator
		End Get
		Set
			If (String.Equals(Me._txtCreator, value) = false) Then
				Me.OntxtCreatorChanging(value)
				Me.SendPropertyChanging
				Me._txtCreator = value
				Me.SendPropertyChanged("txtCreator")
				Me.OntxtCreatorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteCreated", DbType:="DateTime")>  _
	Public Property dteCreated() As System.Nullable(Of Date)
		Get
			Return Me._dteCreated
		End Get
		Set
			If (Me._dteCreated.Equals(value) = false) Then
				Me.OndteCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dteCreated = value
				Me.SendPropertyChanged("dteCreated")
				Me.OndteCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtModuleType", DbType:="VarChar(50)")>  _
	Public Property txtModuleType() As String
		Get
			Return Me._txtModuleType
		End Get
		Set
			If (String.Equals(Me._txtModuleType, value) = false) Then
				Me.OntxtModuleTypeChanging(value)
				Me.SendPropertyChanging
				Me._txtModuleType = value
				Me.SendPropertyChanged("txtModuleType")
				Me.OntxtModuleTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isActive", DbType:="Bit")>  _
	Public Property isActive() As System.Nullable(Of Boolean)
		Get
			Return Me._isActive
		End Get
		Set
			If (Me._isActive.Equals(value) = false) Then
				Me.OnisActiveChanging(value)
				Me.SendPropertyChanging
				Me._isActive = value
				Me.SendPropertyChanged("isActive")
				Me.OnisActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblModule_tblMLAccess", Storage:="_tblMLAccesses", ThisKey:="pkiModuleID", OtherKey:="fkiModuleID")>  _
	Public Property tblMLAccesses() As EntitySet(Of tblMLAccess)
		Get
			Return Me._tblMLAccesses
		End Get
		Set
			Me._tblMLAccesses.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_tblMLAccesses(ByVal entity As tblMLAccess)
		Me.SendPropertyChanging
		entity.tblModule = Me
	End Sub
	
	Private Sub detach_tblMLAccesses(ByVal entity As tblMLAccess)
		Me.SendPropertyChanging
		entity.tblModule = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblRoles")>  _
Partial Public Class tblRole
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiRoleID As Integer
	
	Private _txtRole As String
	
	Private _blnAdd As System.Nullable(Of Boolean)
	
	Private _blnEdit As System.Nullable(Of Boolean)
	
	Private _blnDelete As System.Nullable(Of Boolean)
	
	Private _blnUpdate As System.Nullable(Of Boolean)
	
	Private _txtCreator As String
	
	Private _dteCreated As System.Nullable(Of Date)
	
	Private _isActive As System.Nullable(Of Boolean)
	
	Private _dteDeactivated As System.Nullable(Of Date)
	
	Private _tblUsers As EntitySet(Of tblUser)
	
	Private _tblMLAccesses As EntitySet(Of tblMLAccess)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiRoleIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiRoleIDChanged()
    End Sub
    Partial Private Sub OntxtRoleChanging(value As String)
    End Sub
    Partial Private Sub OntxtRoleChanged()
    End Sub
    Partial Private Sub OnblnAddChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnblnAddChanged()
    End Sub
    Partial Private Sub OnblnEditChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnblnEditChanged()
    End Sub
    Partial Private Sub OnblnDeleteChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnblnDeleteChanged()
    End Sub
    Partial Private Sub OnblnUpdateChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnblnUpdateChanged()
    End Sub
    Partial Private Sub OntxtCreatorChanging(value As String)
    End Sub
    Partial Private Sub OntxtCreatorChanged()
    End Sub
    Partial Private Sub OndteCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteCreatedChanged()
    End Sub
    Partial Private Sub OnisActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisActiveChanged()
    End Sub
    Partial Private Sub OndteDeactivatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDeactivatedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblUsers = New EntitySet(Of tblUser)(AddressOf Me.attach_tblUsers, AddressOf Me.detach_tblUsers)
		Me._tblMLAccesses = New EntitySet(Of tblMLAccess)(AddressOf Me.attach_tblMLAccesses, AddressOf Me.detach_tblMLAccesses)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiRoleID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property pkiRoleID() As Integer
		Get
			Return Me._pkiRoleID
		End Get
		Set
			If ((Me._pkiRoleID = value)  _
						= false) Then
				Me.OnpkiRoleIDChanging(value)
				Me.SendPropertyChanging
				Me._pkiRoleID = value
				Me.SendPropertyChanged("pkiRoleID")
				Me.OnpkiRoleIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtRole", DbType:="VarChar(50)")>  _
	Public Property txtRole() As String
		Get
			Return Me._txtRole
		End Get
		Set
			If (String.Equals(Me._txtRole, value) = false) Then
				Me.OntxtRoleChanging(value)
				Me.SendPropertyChanging
				Me._txtRole = value
				Me.SendPropertyChanged("txtRole")
				Me.OntxtRoleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_blnAdd", DbType:="Bit")>  _
	Public Property blnAdd() As System.Nullable(Of Boolean)
		Get
			Return Me._blnAdd
		End Get
		Set
			If (Me._blnAdd.Equals(value) = false) Then
				Me.OnblnAddChanging(value)
				Me.SendPropertyChanging
				Me._blnAdd = value
				Me.SendPropertyChanged("blnAdd")
				Me.OnblnAddChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_blnEdit", DbType:="Bit")>  _
	Public Property blnEdit() As System.Nullable(Of Boolean)
		Get
			Return Me._blnEdit
		End Get
		Set
			If (Me._blnEdit.Equals(value) = false) Then
				Me.OnblnEditChanging(value)
				Me.SendPropertyChanging
				Me._blnEdit = value
				Me.SendPropertyChanged("blnEdit")
				Me.OnblnEditChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_blnDelete", DbType:="Bit")>  _
	Public Property blnDelete() As System.Nullable(Of Boolean)
		Get
			Return Me._blnDelete
		End Get
		Set
			If (Me._blnDelete.Equals(value) = false) Then
				Me.OnblnDeleteChanging(value)
				Me.SendPropertyChanging
				Me._blnDelete = value
				Me.SendPropertyChanged("blnDelete")
				Me.OnblnDeleteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_blnUpdate", DbType:="Bit")>  _
	Public Property blnUpdate() As System.Nullable(Of Boolean)
		Get
			Return Me._blnUpdate
		End Get
		Set
			If (Me._blnUpdate.Equals(value) = false) Then
				Me.OnblnUpdateChanging(value)
				Me.SendPropertyChanging
				Me._blnUpdate = value
				Me.SendPropertyChanged("blnUpdate")
				Me.OnblnUpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCreator", DbType:="VarChar(50)")>  _
	Public Property txtCreator() As String
		Get
			Return Me._txtCreator
		End Get
		Set
			If (String.Equals(Me._txtCreator, value) = false) Then
				Me.OntxtCreatorChanging(value)
				Me.SendPropertyChanging
				Me._txtCreator = value
				Me.SendPropertyChanged("txtCreator")
				Me.OntxtCreatorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteCreated", DbType:="DateTime")>  _
	Public Property dteCreated() As System.Nullable(Of Date)
		Get
			Return Me._dteCreated
		End Get
		Set
			If (Me._dteCreated.Equals(value) = false) Then
				Me.OndteCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dteCreated = value
				Me.SendPropertyChanged("dteCreated")
				Me.OndteCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isActive", DbType:="Bit")>  _
	Public Property isActive() As System.Nullable(Of Boolean)
		Get
			Return Me._isActive
		End Get
		Set
			If (Me._isActive.Equals(value) = false) Then
				Me.OnisActiveChanging(value)
				Me.SendPropertyChanging
				Me._isActive = value
				Me.SendPropertyChanged("isActive")
				Me.OnisActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDeactivated", DbType:="DateTime")>  _
	Public Property dteDeactivated() As System.Nullable(Of Date)
		Get
			Return Me._dteDeactivated
		End Get
		Set
			If (Me._dteDeactivated.Equals(value) = false) Then
				Me.OndteDeactivatedChanging(value)
				Me.SendPropertyChanging
				Me._dteDeactivated = value
				Me.SendPropertyChanged("dteDeactivated")
				Me.OndteDeactivatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblRole_tblUser", Storage:="_tblUsers", ThisKey:="pkiRoleID", OtherKey:="fkiRoleID")>  _
	Public Property tblUsers() As EntitySet(Of tblUser)
		Get
			Return Me._tblUsers
		End Get
		Set
			Me._tblUsers.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblRole_tblMLAccess", Storage:="_tblMLAccesses", ThisKey:="pkiRoleID", OtherKey:="fkiRoleID")>  _
	Public Property tblMLAccesses() As EntitySet(Of tblMLAccess)
		Get
			Return Me._tblMLAccesses
		End Get
		Set
			Me._tblMLAccesses.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_tblUsers(ByVal entity As tblUser)
		Me.SendPropertyChanging
		entity.tblRole = Me
	End Sub
	
	Private Sub detach_tblUsers(ByVal entity As tblUser)
		Me.SendPropertyChanging
		entity.tblRole = Nothing
	End Sub
	
	Private Sub attach_tblMLAccesses(ByVal entity As tblMLAccess)
		Me.SendPropertyChanging
		entity.tblRole = Me
	End Sub
	
	Private Sub detach_tblMLAccesses(ByVal entity As tblMLAccess)
		Me.SendPropertyChanging
		entity.tblRole = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblMLAccess")>  _
Partial Public Class tblMLAccess
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pkiAccessID As Integer
	
	Private _fkiModuleID As Integer
	
	Private _fkiRoleID As Integer
	
	Private _txtCreatedBy As String
	
	Private _dteCreated As System.Nullable(Of Date)
	
	Private _isActive As System.Nullable(Of Boolean)
	
	Private _dteDeactivated As System.Nullable(Of Date)
	
	Private _tblRole As EntityRef(Of tblRole)
	
	Private _tblModule As EntityRef(Of tblModule)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpkiAccessIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnpkiAccessIDChanged()
    End Sub
    Partial Private Sub OnfkiModuleIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnfkiModuleIDChanged()
    End Sub
    Partial Private Sub OnfkiRoleIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnfkiRoleIDChanged()
    End Sub
    Partial Private Sub OntxtCreatedByChanging(value As String)
    End Sub
    Partial Private Sub OntxtCreatedByChanged()
    End Sub
    Partial Private Sub OndteCreatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteCreatedChanged()
    End Sub
    Partial Private Sub OnisActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnisActiveChanged()
    End Sub
    Partial Private Sub OndteDeactivatedChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OndteDeactivatedChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._tblRole = CType(Nothing, EntityRef(Of tblRole))
		Me._tblModule = CType(Nothing, EntityRef(Of tblModule))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pkiAccessID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property pkiAccessID() As Integer
		Get
			Return Me._pkiAccessID
		End Get
		Set
			If ((Me._pkiAccessID = value)  _
						= false) Then
				Me.OnpkiAccessIDChanging(value)
				Me.SendPropertyChanging
				Me._pkiAccessID = value
				Me.SendPropertyChanged("pkiAccessID")
				Me.OnpkiAccessIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiModuleID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property fkiModuleID() As Integer
		Get
			Return Me._fkiModuleID
		End Get
		Set
			If ((Me._fkiModuleID = value)  _
						= false) Then
				If Me._tblModule.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnfkiModuleIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiModuleID = value
				Me.SendPropertyChanged("fkiModuleID")
				Me.OnfkiModuleIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fkiRoleID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property fkiRoleID() As Integer
		Get
			Return Me._fkiRoleID
		End Get
		Set
			If ((Me._fkiRoleID = value)  _
						= false) Then
				If Me._tblRole.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnfkiRoleIDChanging(value)
				Me.SendPropertyChanging
				Me._fkiRoleID = value
				Me.SendPropertyChanged("fkiRoleID")
				Me.OnfkiRoleIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_txtCreatedBy", DbType:="VarChar(50)")>  _
	Public Property txtCreatedBy() As String
		Get
			Return Me._txtCreatedBy
		End Get
		Set
			If (String.Equals(Me._txtCreatedBy, value) = false) Then
				Me.OntxtCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._txtCreatedBy = value
				Me.SendPropertyChanged("txtCreatedBy")
				Me.OntxtCreatedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteCreated", DbType:="DateTime")>  _
	Public Property dteCreated() As System.Nullable(Of Date)
		Get
			Return Me._dteCreated
		End Get
		Set
			If (Me._dteCreated.Equals(value) = false) Then
				Me.OndteCreatedChanging(value)
				Me.SendPropertyChanging
				Me._dteCreated = value
				Me.SendPropertyChanged("dteCreated")
				Me.OndteCreatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isActive", DbType:="Bit")>  _
	Public Property isActive() As System.Nullable(Of Boolean)
		Get
			Return Me._isActive
		End Get
		Set
			If (Me._isActive.Equals(value) = false) Then
				Me.OnisActiveChanging(value)
				Me.SendPropertyChanging
				Me._isActive = value
				Me.SendPropertyChanged("isActive")
				Me.OnisActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dteDeactivated", DbType:="DateTime")>  _
	Public Property dteDeactivated() As System.Nullable(Of Date)
		Get
			Return Me._dteDeactivated
		End Get
		Set
			If (Me._dteDeactivated.Equals(value) = false) Then
				Me.OndteDeactivatedChanging(value)
				Me.SendPropertyChanging
				Me._dteDeactivated = value
				Me.SendPropertyChanged("dteDeactivated")
				Me.OndteDeactivatedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblRole_tblMLAccess", Storage:="_tblRole", ThisKey:="fkiRoleID", OtherKey:="pkiRoleID", IsForeignKey:=true)>  _
	Public Property tblRole() As tblRole
		Get
			Return Me._tblRole.Entity
		End Get
		Set
			Dim previousValue As tblRole = Me._tblRole.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._tblRole.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._tblRole.Entity = Nothing
					previousValue.tblMLAccesses.Remove(Me)
				End If
				Me._tblRole.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.tblMLAccesses.Add(Me)
					Me._fkiRoleID = value.pkiRoleID
				Else
					Me._fkiRoleID = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("tblRole")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="tblModule_tblMLAccess", Storage:="_tblModule", ThisKey:="fkiModuleID", OtherKey:="pkiModuleID", IsForeignKey:=true, DeleteOnNull:=true, DeleteRule:="CASCADE")>  _
	Public Property tblModule() As tblModule
		Get
			Return Me._tblModule.Entity
		End Get
		Set
			Dim previousValue As tblModule = Me._tblModule.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._tblModule.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._tblModule.Entity = Nothing
					previousValue.tblMLAccesses.Remove(Me)
				End If
				Me._tblModule.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.tblMLAccesses.Add(Me)
					Me._fkiModuleID = value.pkiModuleID
				Else
					Me._fkiModuleID = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("tblModule")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
